### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by apeforest** [dmlc/mshadow#351]
CI has been failing for several days.:

```
$ pip3 install  --user  cpplint pylint
Downloading/unpacking cpplint
  Downloading cpplint-1.3.0.tar.gz (71kB): 71kB downloaded
  Running setup.py (path:/tmp/pip_build_travis/cpplint/setup.py) egg_info for package cpplint
    
Downloading/unpacking pylint
  Downloading pylint-2.0.0-py3-none-any.whl (732kB): 732kB downloaded
Downloading/unpacking astroid>=2.0.0 (from pylint)
  Downloading astroid-2.0-py3-none-any.whl (163kB): 163kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2482, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2344, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map
```

**Comment by szha** [comment]
This code base has been donated to the Apache MXNet project per [#373](https://github.com/dmlc/mshadow/issues/373), and repo is deprecated. Future development and issue tracking should continue in Apache MXNet.
